
server:
  port: 9070

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Lucifer@23
    url: jdbc:mysql://localhost:3306/spring_security_one
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true